# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build and Release
on: workflow_dispatch
#on:
#  push:
#    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout branch
      uses: actions/checkout@v3
    - name: Setup DotNET6.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore Packages/Dependencies
      run: |
          dotnet restore Natus.Logging.Service\Natus.Logging.Service.csproj
          dotnet restore UnitTest\UnitTest.csproj
    - name: Build Projects
      run: |
          dotnet build --configuration Release --no-restore Natus.Logging.Service\
          dotnet build --configuration Release --no-restore UnitTest\
    - name: Test Project
      run: dotnet test UnitTest\UnitTest.csproj
    - name: Publish files
      run: dotnet publish Natus.Logging.Service\Natus.Logging.Service.csproj -c Release -o release -nologo
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Logging_Service
        path: D:\a\LoggingService\LoggingService\release\

  release:
    name: Release Project
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read  # This is required for actions/checkout
      issues: 'write'
    
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: Logging_Service
      - name: Archive contents
        uses: thedoctor0/zip-release@master
        with:
          filename: site.zip
      - name: Create Release
        id: create_releae
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          # draft: false
          # prerelease: false
      # - name: Upload Release Asset
      #   id: upload-release-asset 
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: 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
      #   with:
      #     upload_url: ${{ steps.create_releae.outputs.upload_url }}
      #     asset_path: ./site.zip
      #     asset_name: loggingservice_v${{ github.run_number }}.zip
      #     asset_content_type: application/zip
