# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Publish Installer

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    env:
      WIX_PUBLISH_DIR: /lic_publish
      wixprojdir: ${{ github.workspace }}\Natus.Logging.Service\Installer

    steps:
    - name: Checkout branch
      uses: actions/checkout@v3
      
    - name: Setup DotNET6.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
  
    - name: Print Dir
      run: echo ${{ github.workspace }}

    - name: Set path for candle and light
      run: echo "C:\Program Files (x86)\WiX Toolset v3.11\bin" >> $GITHUB_PATH
      shell: bash

    # - name: Setup NuGet.exe for use with actions
    #   uses: NuGet/setup-nuget@v1.2.0

    - name: Restore Packages/Dependencies
      run: |
          dotnet restore Natus.Logging.Service\Natus.Logging.Service.csproj
    
    - name: Build Service
      run: dotnet build --configuration Release --no-restore Natus.Logging.Service\

    - name: Publish
      run: |
           dotnet publish Natus.Logging.Service\Natus.Logging.Service.csproj -c Release -o /lic_publish --sc --nologo
  
    - name: Get current date
      id: date
      run: echo ("MSI_FILE_NAME=LicensingService-$(date +'%Y-%m-%d')") >> $env:GITHUB_ENV

    - name: Print publish Dir
      run: ls /lic_publish/

    - name: Create MSI Setup
      run: |
           heat.exe dir /lic_publish -g1 -gg -sfrag -srd -dr INSTALLFOLDER -cg NatusLoggingService -o ${{ github.workspace }}\Natus.Logging.Service\Installer\ComponentsGenerated.wxs -var "env.WIX_PUBLISH_DIR"
           candle.exe -v -ext WixUIExtension %wixprojdir%/*.wxs -out %wixprojdir%\
           light.exe -out %wixprojdir%/${{ env.MSI_FILE_NAME }}.msi %wixprojdir%\*.wixobj -ext WixUIExtension -cultures:en-us -loc %wixprojdir%/common.wxl
      shell: cmd
    - name: Upload Installer
      uses: actions/upload-artifact@v3
      with:
        name: Logging_Service
        path: ${{ env.wixprojdir }}/${{ env.MSI_FILE_NAME }}.msi
        if-no-files-found: error
