# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build a Project
on: workflow_dispatch
#on:
#  push:
#    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: |
          dotnet restore Natus.Logging.Service\Natus.Logging.Service.csproj
          dotnet restore UnitTest\UnitTest.csproj
    - name: Build
      run: |
          dotnet build --configuration Release --no-restore Natus.Logging.Service\
          dotnet build --configuration Release --no-restore UnitTest\
    - name: Test
      run: dotnet test UnitTest\UnitTest.csproj
    - name: Publish files
      run: dotnet publish Natus.Logging.Service\Natus.Logging.Service.csproj -c Release -o release -nologo
      
